# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false

cache: packages

r_binary_packages:
    - knitr
    - rmarkdown

r_packages:
    - covr
    - RPushbullet

after_success:
    - Rscript -e 'library(covr); codecov();'
    - Rscript -e "library(RPushbullet); pbPost(type='note', title='blah', body='body', apikey = "${PB_KEY}", devices="${PB_DEV}")"


